import re
import random
import string
import base64

class LuaObfuscator:
    def __init__(self, code):
        self.code = code
        self.var_map = {}

    def random_name(self, length=8):
        return 'stree_' + ''.join(random.choices(string.ascii_letters, k=length))

    def obfuscate_strings(self, code):
        """Encrypt strings to base64 and add a decoder."""
        def replacer(match):
            s = match.group(1) or match.group(2)
            if not s: return match.group(0)
            encoded = base64.b64encode(s.encode()).decode()
            return f'((function() local b=Instance.new("BindableFunction") b.OnInvoke=function(s) return (game:GetService("HttpService"):DecodeBase64(s)) end return b:Invoke("{encoded}") end)())'
        
        # Simple string regex (doesn't handle all Lua string types perfectly but works for basic ones)
        return re.sub(r'"(.*?)"|\'(.*?)\'', replacer, code)

    def obfuscate_variables(self, code):
        """Very basic variable renaming (local variables only)."""
        locals_found = re.findall(r'local\s+([a-zA-Z_][a-zA-Z0-9_]*)', code)
        for var in set(locals_found):
            if var not in self.var_map:
                self.var_map[var] = self.random_name()
            code = re.compile(r'\b' + var + r'\b').sub(self.var_map[var], code)
        return code

    def add_junk_code(self, code):
        junk = [
            f"-- Generated by Stree Obfuscator v1.0\n",
            f"local {self.random_name()} = {random.randint(1000, 9999)}\n",
            f"if false then print('{self.random_name()}') end\n"
        ]
        return "".join(junk) + code

    def run(self):
        print("Obfuscating code...")
        code = self.add_junk_code(self.code)
        code = self.obfuscate_variables(code)
        # code = self.obfuscate_strings(code) # String obfuscation is complex for standard Lua, keeping it simple
        return code

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python obfuscator.py <input_file> [output_file]")
    else:
        input_file = sys.argv[1]
        output_file = sys.argv[2] if len(sys.argv) > 2 else "obfuscated.lua"
        
        with open(input_file, 'r') as f:
            source = f.read()
            
        obf = LuaObfuscator(source)
        result = obf.run()
        
        with open(output_file, 'w') as f:
            f.write(result)
        print(f"Successfully obfuscated to {output_file}")
